# change the followings to match your Github username and repo name
baseurl: "" # the name of your github repo
url: "https://kuwarehouse.github.io" # the url of your github pages

# site information used in page title, meta data etc.
title: "KuWarehouse"
description: KuWarehouse.com

# color theme for links
theme-color: indigo # indigo|yellow|pink|green|stone|

# homepage information
author: false
author-bio: Handmade Wood Objects # change to false to hide
author-image: ku-logo.png  # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: true

nav-menu:
- text: About
  permalink: about
- text: Blog
  permalink: blog

# use false to turn off any social media links
twitter: false
store: https://www.etsy.com/shop/KuWarehouse
eth: false
facebook: false
instagram: https://www.instagram.com/ku_warehouse_store/
github: false
linkedin: false
medium: false
google-scholar: false
email: mailto:harryjwang@gmail.com

# footer information
footer-msg: "Powered by Tailpages"
footer-msg-link: https://github.com/harrywang/tailpages

# google analytics
google-analytics: G-9P4ZVR91TM

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
